In [1]:
import numpy as np

In [2]:
a = np.concatenate(([3],[0]*5, np.arange(-1,1.002, 2/9.0)))

In [3]:
a

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [7]:
ab = np.r_[3, [0]*5, -1:1:10j]

In [8]:
ab

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [9]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [10]:
np.mgrid[0:5:4j,0:5:4j]

array([[[0.        , 0.        , 0.        , 0.        ],
        [1.66666667, 1.66666667, 1.66666667, 1.66666667],
        [3.33333333, 3.33333333, 3.33333333, 3.33333333],
        [5.        , 5.        , 5.        , 5.        ]],

       [[0.        , 1.66666667, 3.33333333, 5.        ],
        [0.        , 1.66666667, 3.33333333, 5.        ],
        [0.        , 1.66666667, 3.33333333, 5.        ],
        [0.        , 1.66666667, 3.33333333, 5.        ]]])

In [11]:
from numpy import poly1d

In [13]:
p = poly1d([3,4,5])

In [14]:
p

poly1d([3, 4, 5])

In [15]:
print(p)

   2
3 x + 4 x + 5


In [16]:
p.deriv()

poly1d([6, 4])

In [17]:
p([4,5])

array([ 69, 100])

In [18]:

p([7,5])

array([180, 100])

In [20]:
def addsubtract(a,b):
    if  a > b:
        return a - b
    else:
        return a + b

In [21]:
vec_addsubtract = np.vectorize(addsubtract)

In [22]:
vec_addsubtract([0,3,6,9],[1,3,5,7])

array([1, 6, 1, 2])

In [23]:
x = np.arange(10)

In [24]:
condlist = [x<3, x>5]

In [25]:
condlist

[array([ True,  True,  True, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False, False,  True,  True,  True,
         True])]

In [26]:
choicelist = [x, x**2]
np.select(condlist, choicelist)

array([ 0,  1,  2,  0,  0,  0, 36, 49, 64, 81])

In [27]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])