In [1]:
range(10)

range(0, 10)

In [2]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
list(range(0,20,2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:

list(range(20,2))

[]

In [7]:
range(0,10)

range(0, 10)

In [9]:
list(range(20,2))

[]

In [10]:
equiv_anon = lambda x: x*2

In [11]:
equiv_anon(3)

6

In [12]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

In [13]:
ints = [4,0,1,5,6]

In [14]:
apply_to_list(ints, lambda x: x*2)

[8, 0, 2, 10, 12]

In [15]:
import numpy as np

In [18]:
A = np.arange(1,10).reshape(3,3)

In [19]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
A[0:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [22]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [23]:
A[1:, :]

array([[4, 5, 6],
       [7, 8, 9]])

In [24]:
A[1,:2]

array([4, 5])