In [1]:
import pandas as pd
import numpy as np

In [3]:
M = np.array([[1,2],[3,4]])

In [4]:
L = [[1,2],[3,4]]

In [5]:
L[0]

[1, 2]

In [6]:
M[0]

array([1, 2])

In [7]:
M2 = np.matrix([[1,2],[3,4]])

In [8]:
M2

matrix([[1, 2],
        [3, 4]])

In [9]:
M

array([[1, 2],
       [3, 4]])

In [10]:
Z = np.zeros(10)

In [11]:
Z


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
Z = np.zeros((10,10))

In [13]:
O = np.ones((10,10))

In [14]:
R = np.random.random((10,10))

In [15]:
G = np.random.randn(10,10)

In [16]:
G

array([[ 1.44295137e-01,  1.21747810e+00,  9.81950590e-01,
         7.43100035e-01,  1.93054255e+00, -1.56276500e+00,
         3.79697171e-01,  3.14344038e-01,  1.11396687e+00,
        -7.68696069e-01],
       [-3.03529580e-01,  1.81776586e+00,  1.51529785e+00,
         2.00207241e-01, -2.50010363e+00, -1.28767647e+00,
         1.65234224e-01,  1.47264679e+00, -1.90271523e+00,
        -3.51378747e-01],
       [ 1.56823095e+00, -4.82305185e-01, -1.81591170e-02,
        -6.30633522e-01, -7.73287544e-01, -9.14197144e-01,
         1.16788227e-02,  1.19449358e+00, -3.36599039e-02,
        -3.00103876e-01],
       [ 1.41862354e+00,  7.50762656e-01, -3.80301567e-01,
        -1.14272573e+00, -1.27700996e+00,  2.89502983e-01,
        -9.21989908e-01,  4.48495630e-01, -1.67946105e+00,
         1.52932821e-01],
       [-1.35151827e+00, -5.85381280e-01,  1.85667438e-01,
        -5.11508911e-01, -8.99189667e-01,  1.42683712e+00,
         1.90517405e+00,  7.09000934e-01, -1.14476874e+00,
         5.

In [17]:
G.mean()

0.12508471173947547

In [19]:
G.std()

1.064682426125449

In [20]:
A = np.array([[1,2],[3,4]])

In [21]:
Ainv = np.linalg.inv(A)

In [22]:
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [23]:
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [24]:
np.linalg.det(A)

-2.0000000000000004

In [25]:
np.diag(A)

array([1, 4])

In [26]:
a = np.array([1,2])
b = np.array([3,4])


In [27]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [28]:
np.inner(a,b)

11

In [29]:
a.dot(b)

11

In [30]:
X = np.random.randn(100,3)

In [32]:
cov = np.cov(X)


In [34]:
cov.shape

(100, 100)

In [35]:
covT = np.cov(X.T)

In [36]:
covT

array([[ 0.97410608, -0.02964809,  0.07964859],
       [-0.02964809,  0.87174203, -0.03296044],
       [ 0.07964859, -0.03296044,  1.1509782 ]])

In [37]:
np.linalg.eigh(covT)

(array([0.86322448, 0.94658996, 1.18701187]),
 array([[ 0.22484031,  0.90413959, -0.36328838],
        [ 0.97315099, -0.18952386,  0.13060574],
        [ 0.04923401, -0.38289988, -0.92247693]]))

In [38]:
A

array([[1, 2],
       [3, 4]])

In [39]:
b

array([3, 4])

In [40]:
b = np.array([1,2])

In [43]:
b

array([1, 2])

In [41]:
x = np.linalg.inv(A).dot(b)

In [42]:
x

array([2.22044605e-16, 5.00000000e-01])

In [44]:
x = np.linalg.solve(A,b)

In [45]:

x

array([0. , 0.5])