In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [7]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

/home/ma/.bin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2],axis=1, keys=['cat1','cat2'])

/home/ma/.bin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [15]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [16]:
dframe1

X         Y         Z
0  1.380767  1.369638 -2.348482
1  0.399236 -1.667561  0.973581
2  0.551540  0.076141  1.271389
3 -1.309606  0.098321  0.143362

In [17]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [18]:
pd.concat([dframe1, dframe2])

/home/ma/.bin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  1.380767  1.369638 -2.348482
1       NaN  0.399236 -1.667561  0.973581
2       NaN  0.551540  0.076141  1.271389
3       NaN -1.309606  0.098321  0.143362
0 -1.711807  1.139509  0.116734       NaN
1  1.918544  0.193387 -1.685853       NaN
2 -0.073462  0.349052  0.965691       NaN

In [19]:
pd.concat([dframe1, dframe2], ignore_index=True)

/home/ma/.bin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  1.380767  1.369638 -2.348482
1       NaN  0.399236 -1.667561  0.973581
2       NaN  0.551540  0.076141  1.271389
3       NaN -1.309606  0.098321  0.143362
4 -1.711807  1.139509  0.116734       NaN
5  1.918544  0.193387 -1.685853       NaN
6 -0.073462  0.349052  0.965691       NaN

In [21]:
ser1 = Series([2,np.nan,4, np.nan, 6, np.nan],
             index=['Q','R','S','T','U','V'])

In [23]:
ser2 = Series(np.arange(len(ser1)),dtype=np.float64,
             index=['Q','R','S','T','U','V'])

In [25]:
index = np.where(pd.isnull(ser1),ser2,ser1)