In [1]:
range(8)

range(0, 8)

In [4]:
for a in range(0,10):
    print(a)  

0
1
2
3
4
5
6
7
8
9


In [5]:
import numpy as np

In [13]:
A = np.arange(9).reshape(3,3)

In [14]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
A[:,1]

array([1, 4, 7])

In [17]:
A[0,-1]

2

In [18]:
A[0,:]

array([0, 1, 2])

In [19]:
B = np.random.randn(9).reshape(3,3)

In [20]:
B

array([[ 0.70539598,  0.10464147,  0.5446841 ],
       [-0.8019492 , -0.20628699,  1.26830946],
       [-0.07273024, -2.39416567, -1.24568718]])

In [21]:
A[0,1]

1

In [22]:
A[0,2]

2

In [24]:
AA = np.matrix([3,3])

In [25]:
AA

matrix([[3, 3]])

In [26]:
np.ndarray((2,2))

array([[6.01433264e+175, 6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180]])

In [27]:
B.T

array([[ 0.70539598, -0.8019492 , -0.07273024],
       [ 0.10464147, -0.20628699, -2.39416567],
       [ 0.5446841 ,  1.26830946, -1.24568718]])

In [28]:
B[1,0]

-0.8019491984393491

In [29]:
B

array([[ 0.70539598,  0.10464147,  0.5446841 ],
       [-0.8019492 , -0.20628699,  1.26830946],
       [-0.07273024, -2.39416567, -1.24568718]])

In [31]:
AA = np.matrix([[1,2,3],
              [4,5,6],
                [7,8,9]])

In [32]:
AA

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
b= np.array([1,2,3])

In [35]:
AA*b.T

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)